### ISSUE TITLE
Need more questions!!

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#1]
I'm thinking somewhere around 5 questions per chapter depending on the length/difficulty of the chapter, but open to suggestions!

All of the current questions can be found here: https://github.com/austintackaberry/ydkjs-exercises/blob/master/src/data

**Drop a comment here if you are working on adding questions to a certain chapter, so that we don't have multiple people working on adding questions to the same chapter**

**Up & Going**
- [x] Chapter 1: Into Programming
- [x] Chapter 2: Into JavaScript

**Scope & Closures**
- [x] Chapter 1: What is Scope?
- [x] Chapter 2: Lexical Scope
- [x] Chapter 3: Function vs. Block Scope
- [x] Chapter 4: Hoisting
- [x] Chapter 5: Scope Closures

**this & Object Prototypes**
- [x] Chapter 1: this Or That?
- [x] Chapter 2: this All Makes Sense Now!
- [x] Chapter 3: Objects
- [x] Chapter 4: Mixing (Up) "Class" Objects
- [x] Chapter 5: Prototypes
- [x] Chapter 6: Behavior Delegation

**Types & Grammar**
- [x] Chapter 1: Types
- [x] Chapter 2: Values
- [x] Chapter 3: Natives
- [x] Chapter 4: Coercion
- [x] Chapter 5: Grammar

**Async & Performance**
- [x] Chapter 1: Asynchrony: Now & Later
- [x] Chapter 2: Callbacks
- [x] Chapter 3: Promises
- [x] Chapter 4: Generators
- [x] Chapter 5: Program Performance
- [x] Chapter 6: Benchmarking & Tuning

**ES6 & Beyond**
- [x] Chapter 1: ES? Now & Future
- [x] Chapter 2: Syntax
- [x] Chapter 3: Organization
- [x] Chapter 4: Async Flow Control
- [x] Chapter 5: Collections
- [x] Chapter 6: API Additions
- [x] Chapter 7: Meta Programming
- [x] Chapter 8: Beyond ES6

**Comment by austintackaberry** [comment]
Up and Going now has 40 questions! Thanks to everyone who contributed! 

I think we are now at the point where we shouldn't accept PRs that increase the number of questions for Up and Going. We still desperately need questions for all other books!

**Comment by hakabuk** [comment]
I'm currently working on questions for chapter 2 of Scope and Closure

**Comment by austintackaberry** [comment]
I will be working on Scope and Closures Ch2-5

**Comment by austintackaberry** [comment]
I will be finishing up Scope & Closures, and then starting on this & Object Prototypes

**Comment by austintackaberry** [comment]
Moving on to Types & Grammar!

**Comment by austintackaberry** [comment]
Onto async and performance

**Comment by austintackaberry** [comment]
ES6...and beyond!

**Comment by austintackaberry** [comment]
Certainly we will add/delete questions in the future, but the purpose of this issue was to get to a point where we had a respectable amount of questions for each chapter, and I think we're there!
