### ISSUE TITLE
incorrect question(s)

### ISSUE THREAD

**Issue by nikrb** [austintackaberry/ydkjs-exercises#101]
Just testing (an unrelated) pr and I noticed question has two correct answer options
book: Up & Going
chapter: 1 into programming
question: 7
First and third answer options are identical, for the purposes of the question.

Opening this issue as we should check through all the questions at some point - so if you find an issue with a question, please add it as a comment

**Comment by hakabuk** [comment]
I fixed this one just now (I added it to one of the existing PRs), but having one thread for all typos/ small issues is a great idea, and I agree that a thorough question check will be necessary at some point.

**Comment by austintackaberry** [comment]
Thanks for opening this issue. I don't have an issue with just opening up a new issue whenever they are found no matter how small they are. They are easier to track that way.

**Comment by nikrb** [comment]
ok makes sense. Shall we leave this open as a reminder it needs doing? I don't have a problem if you'd rather close it

**Comment by austintackaberry** [comment]
I understand your point about leaving it open to remind people to constantly check for mistakes, but I prefer to only have open issues for known issues. Maybe the `CONTRIBUTING.md` would be a good place for that?

**Comment by nikrb** [comment]
good point
