### ISSUE TITLE
Book and chapter links should be black

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#103]
The links to the books and chapters are blue on the main page and on the sidebar, but they should be black.

![screenshot from 2018-06-28 23-37-48](https://user-images.githubusercontent.com/29493001/42077048-6d92d3a4-7b2c-11e8-877d-5295d839aef4.png)

**Comment by hakabuk** [comment]
Since it's a minor change, I added the colour change to an existing PR. I hope it's OK

**Comment by nikrb** [comment]
lol slapped wrist for you 😉

**Comment by hakabuk** [comment]
Sorry about the mixup... On second thought it's best to leave this open for someone else to fix - this way they can discover this repo, which is a great way to learn JS! :)

**Comment by austintackaberry** [comment]
Thanks @hagnerd!
