### ISSUE TITLE
Submit, explanation, and submit result are all on top of each other with no margin/padding

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#107]
![screenshot from 2018-07-01 16-56-47](https://user-images.githubusercontent.com/29493001/42140173-131d29bc-7d50-11e8-82d2-c52106503c34.png)

Easy fix is to just add margin, but I still think there is room for improvement on the design. Thoughts?

**Comment by oliverJurgen** [comment]
Can I submit a pull request adding the margins?

**Comment by austintackaberry** [comment]
Thanks @oliverJurgen! :tada:
