### ISSUE TITLE
Where should we put the link to our Discord server?

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#112]
Opening this issue partially just to make sure that everyone sees that we have a Discord server:

https://discord.gg/F9Cs5tW

But also because I'm not sure exactly where we should put the link. Currently it is in the readme under Current Status. I'm not sure it is the right place, and if it is, then it probably deserves more verbiage to explain who should join and why.

**Comment by radotreyes** [comment]
I think where it is is fine, maybe bold it or make it its own header with a link and a short blurb under it.

Besides putting it in the readme, how about coding an "about" page to put in the app?

**Comment by austintackaberry** [comment]
An About page seems like a good idea. I'm not sure where we would put the link to it, but that's something we could discuss. Want to open an issue?
