### ISSUE TITLE
'Next' button lets the user move on to the next question even if incorrect/no answer submitted

### ISSUE THREAD

**Issue by mdncs** [austintackaberry/ydkjs-exercises#113]
When taking tests or quizzes, you normally have to provide an answer (often a correct one) in order to progress to the next question. 

Also, when questions are finished there would be nice to replace the 'next' button with a 'next chapter' one? Off the top of my head that could be done by checking if index of the question is last in array but maybe someone has an simpler idea.

**Comment by nikrb** [comment]
I think the plan is to allow the users to move freely through the questions.

Next chapter would be a nice touch.
Should previous button (at question one) be previous chapter?

**Comment by radotreyes** [comment]
Yeah, next/previous chapter would be good. Even if redundant because of the sidebar, on mobile the sidebar will most likely not be there, so we might as well have that redundancy in place.

**Comment by austintackaberry** [comment]
Next chapter is definitely a good idea. Thanks @mdncs! I'm not sold on previous chapter...what would the use case be? Maybe if the user clicks next chapter, but didn't mean to? Would the "previous chapter" button take you to the last question of the previous chapter or the first question of the previous chapter?

Also, I think we can rely on the user having access to a simplified sidebar on mobile that would at least have links to the chapters.

**Comment by austintackaberry** [comment]
Closing because I created a new issue for this #180
