### ISSUE TITLE
Should the sidebar be resizable and have a toggle?

### ISSUE THREAD

**Issue by radotreyes** [austintackaberry/ydkjs-exercises#114]
I think it would be nice to have a resizable and togglable sidebar.

Right now, it is dynamically resizing (width defined with `vw`), but it's clunky. Being able to simply drag and resize the component would improve the UX a good amount. Also, adding in a typical hamburger icon with the expected slide in/out behavior kind of ties into this.

If we think it's a good idea, I can take care of this issue, unless anyone else would like to snatch it up.

**Comment by austintackaberry** [comment]
Honestly, I don't know if we need it to have a toggle or be resizable on desktop. We should definitely convert it into a hamburger at a certain viewport width, but other than that I don't think it is necessary. The questions don't take up that much space, so I would think the user would always want the sidebar visible on desktop.

I'm open to it if others disagree though

**Comment by austintackaberry** [comment]
In mobile we could have a toggle for the sidebar, but maybe have it be full screen? There isn't a whole lot of width to phones these days, so a sidebar that isn't full width might be difficult.

**Comment by radotreyes** [comment]
I'm good with that. 

For mobile, I like how Twitter does it (shameless plug):
![image](https://user-images.githubusercontent.com/25578179/42361924-b583391e-80a5-11e8-8117-a2978228c4f6.png)

**Comment by austintackaberry** [comment]
Closing because decision has been made about what we want to do, see #143
