### ISSUE TITLE
Fix tests to not test implementation details

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#119]
Our tests are fragile and will break if we change question/answer text, number of `<span>`s, colors, etc.

Utilizing `data-test-...` attributes are a good way to fix this issue:

https://blog.kentcdodds.com/making-your-ui-tests-resilient-to-change-d37a6ee37269

**Comment by nikrb** [comment]
can we fix this by not using our real data ... tests should define their own test data surely? Thanx for the link will check it out later.

**Comment by austintackaberry** [comment]
That won't fix the issue. Using real data isn't necessarily an issue. Fake data can be good because it could catch errors before they bite you, but real data is good because it more closely represents your actual app.

The main issue with our tests as they stand is that they find virtual DOM nodes by traversal. If we are testing that a node has a value of x, and we decide to move that node to a different spot, our tests shouldn't break.

We are also currently relying on a certain number of `<span />`s, even relying on their order. So if we add one `<span />` at the top of the page, several tests will fail.

Using data-attributes will solve just about all of these problems. Also, it would probably be a good idea to not use shallow rendering.

**Comment by nikrb** [comment]
ok I'm happy to move to data-attributes.
That bit you tacked onto the end, why not use shallow rendering?

**Comment by nikrb** [comment]
there is an iterator unique key warning for book.id on test. Had a look and it seems book id is set when we render the book routes - seems weird. Is there a reason we don't have an id in the data files?
Just thinking it'd be nice not to have the warning on (Sidebar) test.

**Comment by austintackaberry** [comment]
What if you rename a React component or add a wrapper inside of it? Both of those actions will break shallowly rendered tests.

https://blog.kentcdodds.com/write-tests-not-too-many-mostly-integration-5e8c7fff591c

**Comment by hagnerd** [comment]
I know this would be a substantial rewrite of all the current testing, but have you thought about using [react-testing-library](https://github.com/kentcdodds/react-testing-library) instead of Enzyme?

In my experience it has allowed me to test user-focused issues vs implementation details. It also works really well with testing render props components.

**Comment by austintackaberry** [comment]
Yes! That would be awesome. I am not opposed to doing this in Enzyme, but if you or someone else would like to start moving over to react-testing-library, then I am all for it!

**Comment by hagnerd** [comment]
I’d love to get a start on that tonight.

**Comment by hagnerd** [comment]
Here is an [example gist](https://gist.github.com/hagnerd/02fbfb1451e5dac33ed790f3da531f06) showing how I would re-write the current test for BookHome.js using react-testing-library (minus the implementation details). I added a lot of comments throughout the test to highlight some of the important things.

**Comment by austintackaberry** [comment]
Looks great, I'm all in!
