### ISSUE TITLE
Add no-console to eslint rules

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#123]
We should not be writing to the console in production, so we should add the `no-console` eslint rule to our config.

**Comment by nirmalks** [comment]
Hi @austintackaberry 

I have a couple of queries. 

1. After adding the rule, should it also throw an error during "npm run dev"? 	
2. Should the log statements inside registerServiceWorker.js be retained?

**Comment by austintackaberry** [comment]
#207
