### ISSUE TITLE
Update existing questions/answers that have code to use markdown

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#128]
There are many questions that have code that is not formatted. Now that we have markdown support, we should be styling them as code using markdown.

- [x] /up-going/ch1/q7
- [x] /up-going/ch1/q8
- [x] /up-going/ch1/q9
- [x] /up-going/ch1/q10
- [x] /up-going/ch1/q11
- [x] /up-going/ch1/q12
- [x] /up-going/ch1/q13
- [x] /up-going/ch2/q3
- [x] /up-going/ch2/q4
- [x] /up-going/ch2/q10
- [x] /up-going/ch2/q11
- [x] /up-going/ch2/q13
- [x] /up-going/ch2/q14
- [x] /up-going/ch2/q15
- [x] /up-going/ch2/q17
- [x] /up-going/ch2/q18
- [x] /up-going/ch2/q19
- [x] /scope-closures/ch1/q5
- [x] /scope-closures/ch1/q6
- [x] /scope-closures/ch1/q8
- [x] /scope-closures/ch1/q12
- [x] /scope-closures/ch1/q13
- [x] /scope-closures/ch1/q14

**Comment by austintackaberry** [comment]
All yours!

**Comment by austintackaberry** [comment]
Thanks @jarrodyellets for fixing a bunch of these!

Looks like there are a couple small ones still left:

- Up & Going / Ch1 / Q8 - question has some unformatted code
- Up & Going / Ch1 / Q10 - `num` should be formatted in the question

**Comment by jarrodyellets** [comment]
I'll take care of these right now
