### ISSUE TITLE
Move to Next and Previous questions with keyboard right and left arrows

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#129]
A user should be able to go to the next question by pressing the keyboard right arrow and go to the previous question by pressing the keyboard left arrow

**Comment by radotreyes** [comment]
Should this behavior span across books/chapters?

For example, if I'm on Chapter 1 and I reach the last question, should pressing the right arrow take me to Chapter 2 Question 1?

**Comment by austintackaberry** [comment]
That's a good question. I would say it should either go to the first question of the next chapter or it should do nothing. I don't have any strong feelings either way atm.

**Comment by austintackaberry** [comment]
Thanks @radotreyes! :tada:
