### ISSUE TITLE
Fix mobile styling for splash page

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#13]
![screenshot from 2018-05-18 00-25-05](https://user-images.githubusercontent.com/29493001/40221673-f46c7428-5a31-11e8-9280-aa9f831f3645.png)

**Comment by austintackaberry** [comment]
Go for it, it's yours!

**Comment by kevinYCKim33** [comment]
<blockquote class="imgur-embed-pub" lang="en" data-id="a/ffFFEG2"><a href="//imgur.com/ffFFEG2"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

Fix attempted by reducing font size from 30 to 25 and also adding lineHeight of 25px

**Comment by kevinYCKim33** [comment]
![](https://i.imgur.com/jKUBnO2.png) 

Fix attempted by changing font size to 25px from 30px and also adding a line height of 25px.

https://github.com/austintackaberry/ydkjs-exercises/pull/20
