### ISSUE TITLE
Book page should show chapters as text align left

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#136]
![screenshot from 2018-08-11 00-51-26](https://user-images.githubusercontent.com/29493001/43989558-d7bfb850-9d00-11e8-9552-cc4390069434.png)
Now they have `text-align: center` which looks odd. The parent element should still be centered, but the list items should have `text-align: left`

**Comment by jarrodyellets** [comment]
I'll tackle this issue

**Comment by jarrodyellets** [comment]
![menu](https://user-images.githubusercontent.com/32344277/45017259-72246100-b027-11e8-93dc-9cdbe0eb2983.jpg)

Would you want this page to be aligned left as well, or just the book page?

**Comment by austintackaberry** [comment]
Sounds good! I think it looks fine centered but I'm open to opinions

**Comment by jarrodyellets** [comment]
![leftmenu](https://user-images.githubusercontent.com/32344277/45087611-d1a56e00-b106-11e8-91b9-fc472d3aa96e.jpg)

Yeah, I agree that centered looks best.

**Comment by austintackaberry** [comment]
#176
