### ISSUE TITLE
Fixing the mobile experience

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#143]
There are many things about the mobile experience that is broken. This issue encompasses all of those problems:

- [x] Sidebar should become togglable when the viewport width is less than a certain value #114
- [x] The footer text should not take up the whole width of the screen. There should be padding/margin or the width should be set to some percentage of the full width.
- [x] The page title + book title + chapter title takes up ~40% of the screen in mobile. We should have responsive font sizes and/or not show all three titles in mobile.
- [x] Answer radio buttons don't always line up with the middle of the corresponding answer
- [x] The answers should have overflow-x: scroll, so that part of the answers don't get cut off

**Comment by austintackaberry** [comment]
Going to start hacking something together

**Comment by designviacode** [comment]
Hey @austintackaberry could you elaborate and explain in some detail on what kind 
of responsive changes are required for the `Home page`, `Book page`, `Chapter page` and `Question page`.

**Comment by austintackaberry** [comment]
**Home Page**

- The footer text should not take up the whole width of the screen. There should be padding/margin or the width should be set to some percentage of the full width.

**Comment by designviacode** [comment]
@austintackaberry Thanks for clarifying. 
I'd like to work on this.

**Comment by TyMichaels** [comment]
Going to hop on this since it seems like it hasn't been resolved yet.

**Comment by austintackaberry** [comment]
Fixed by #231. Thanks @TyMichaels!
