### ISSUE TITLE
Move all "toggling" behavior to render props/Toggle component

### ISSUE THREAD

**Issue by radotreyes** [austintackaberry/ydkjs-exercises#174]
This isn't a true issue, just a thought I have. While implementing the "Show Explanation" behavior for each question, sidebar toggle behavior from #114, and more recently when implementing toggling menus from #102, I noticed that we've been writing a lot of individual toggle states scoped only to a single component for each of these.

That isn't really a problem, but to avoid having to rewrite toggle states in the future, I think we might have a good use case to contain toggling state and behavior inside a single `Toggle` component:

```js
import { Component } from 'react';
import PropTypes from 'prop-types';

export default class Toggle extends Component {
  static propTypes = {
    children: PropTypes.func.isRequired,
    callbacks: PropTypes.array,
    show: PropTypes.bool,
  };

  state = { show: this.props.show };

  handleToggle() {
    const { callbacks } = this.props;
    this.setState(prevState => {
      callbacks && callbacks.forEach(callback => callback());
      return {
        show: !prevState.show,
      };
    });
  }

  render() {
    const { children } = this.props;
    const toggle = () => this.handleToggle();
    return children({ show: this.state.show, toggle });
  }
}
```

Again, this isn't mission critical and no behavior or anything will be changed, for the sake of scalability and any future toggling behavior we might need to implement, I think it might be a good idea to refactor with render props. What are your thoughts?

**Comment by austintackaberry** [comment]
This is an interesting idea...so `show` determines if the component should be visible, `toggle` is the function that toggles `show`. What is the purpose of `callbacks`? Why do the callbacks need to be managed by the toggle component?

**Comment by radotreyes** [comment]
My thought with the callbacks when writing that example was that maybe there would need to be functions that need to run before invoking a toggle; but now that I think about it I think that could probably be managed inside a `componentDidUpdate`, so probably unnecessary. I'll give this implementation a shot and include it in the PR for #102 if it looks good.

**Comment by austintackaberry** [comment]
Sounds good :+1:
