### ISSUE TITLE
Add a "Next Chapter" button for when you are on the last question of a chapter

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#180]
When a user is on the last question of a chapter, there should be a button "Next Chapter" that takes the user to the first question of the next chapter. If the user is on the last chapter of a book, this button should take them to the first question of the first chapter of the next book. This button should replace the "Next" button.

This issue was created as a result of #113

**Comment by syberen** [comment]
I'd like to take this one on

**Comment by austintackaberry** [comment]
Thanks @syberen! #196
