### ISSUE TITLE
Up & Going / Ch2 / Q13 Typo

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#183]
The question reads: "In which of these cases we would probably be safe using == rather than === for comparison?"

But it should read: "In which of these cases would we probably be safe using == rather than === for comparison?"

**Comment by kshitijpurwar** [comment]
So Ironic my fix typo PR title has a title !!

**Comment by kshitijpurwar** [comment]
Typo fixed, PR created

**Comment by austintackaberry** [comment]
#203
