### ISSUE TITLE
Inline code formatting overlaps with lines above and below in the questions

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#189]
This is just one example but there are several

![screenshot from 2018-09-10 23-30-07](https://user-images.githubusercontent.com/29493001/45342034-8b5e6d80-b551-11e8-8371-2cf6ed7fc9d6.png)

There are at least a couple potential solutions. The easiest would be to just increase the line size of text for the questions. This isn't an issue for the answers.

**Comment by jarrodyellets** [comment]
I'll take this one

**Comment by jarrodyellets** [comment]
![answer](https://user-images.githubusercontent.com/32344277/45472263-fbc4e480-b733-11e8-9b2c-2c265ce8da12.jpg)

I'll increase the answer line height a bit as well...some look a little cramped.

**Comment by austintackaberry** [comment]
Sounds good, all yours!
