### ISSUE TITLE
Have a pre-commit script that generates a build and runs tests if the developer opts in

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#191]
Use husky to execute `npm run build` and `npm test` along with `pretty-quick` pre-commit. This should be opt-in. Maybe if the developer wants to opt in to this, they can have a file, /.opt-in that includes "build" and "test" to indicate they would like to generate a build and test pre-commit. If the build fails or if any of the tests fail, then the commit should not occur.

**Comment by radotreyes** [comment]
I'll take a shot at this!

**Comment by austintackaberry** [comment]
:tada: :tada: :tada:
