### ISSUE TITLE
npm reporting a security vulnerability

### ISSUE THREAD

**Issue by JacksonBates** [austintackaberry/ydkjs-exercises#208]
=== npm audit security report ===

Run  `npm install react-dev-utils@6.0.3`  to resolve 1 vulnerability
SEMVER WARNING: Recommended action is a potentially breaking change

found 1 high severity vulnerability in 57204 scanned packages
1 vulnerability requires semver-major dependency updates.

This can be easily fixed, but the implications for possible breaking changes need to be considered.

**Comment by JacksonBates** [comment]
I'm happy to take care of this - I'll check the update changelog for possible breaking changes and fix anything that get's broken if necessary.

**Comment by austintackaberry** [comment]
Thanks for opening this issue! I actually just fixed this in another repo...the react team made security patches for every major version, so you don't have to upgrade the major version.

**Comment by JacksonBates** [comment]
Yeah, I'll open the PR in a sec - I noticed that it only needs the upgrade to 5.0.2, which won't introduce breaking changes.

More than likely, it's not really an issue since the app will load the highest non-breaking change anyway, but the warning in the console when you npm install for the first time could put new contributors off.

**Comment by austintackaberry** [comment]
#210
