### ISSUE TITLE
Keep question box height constant, so that the navigation buttons don't move

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#22]
![awesomescreenshot-2018-05-21t16-02-29-441z](https://user-images.githubusercontent.com/29493001/40317392-35e903a2-5cd6-11e8-9f01-1f369c8ac18d.gif)

**Comment by VikasMadan** [comment]
What do you suggest --
a. Fix the button positions to the bottom? 
or,
b. Give a const height to the box?

**Comment by austintackaberry** [comment]
Maybe just a fixed height for now? We'll have to figure something else out later when we add in the explanations.
