### ISSUE TITLE
Improve mobile content overflow

### ISSUE THREAD

**Issue by TyMichaels** [austintackaberry/ydkjs-exercises#232]
Right now, most of the mobile content is overflowing off the screen (see first image). We can scroll to see it, but it's not ideal. The main source of this problem is that the `pre` elements containing the code snippets don't inherently use word wrapping. 

<img width="431" alt="current" src="https://user-images.githubusercontent.com/5217136/58303287-4b1fe200-7da4-11e9-8506-f218bdf72233.png">

### There are essentially two solutions that I see:
**1. Have the `pre` elements use word wrapping**

<img width="425" alt="wrap-code" src="https://user-images.githubusercontent.com/5217136/58303292-51ae5980-7da4-11e9-8c86-0a4069e485f3.png">

**2. Have only the overflowing sections be scrollable**

![scroll-answers](https://user-images.githubusercontent.com/5217136/58303297-57a43a80-7da4-11e9-8bed-3c4a8acb21bb.gif)

Which solution is preferred?

**Comment by austintackaberry** [comment]
Thanks for opening this issue!

Solution 1 looks like the best user experience to me
