### ISSUE TITLE
Wrong answer marked as correct

### ISSUE THREAD

**Issue by alexigityan** [austintackaberry/ydkjs-exercises#233]
in Async and Performance, chapter 5, shouldn't the following question have id:3 as correct answer? 

 {
    question: `What is **not** a common use for a web worker?`,
    questionId: '7eg8p9TGqQ8TuMwYzmUv',
    shouldBeRandomized: true,
    answers: [
      { text: 'Processing intensive math calculations', id: 0 },
      { text: 'Sorting large data sets', id: 1 },
      { text: 'High-traffic network communications', id: 2 },
      { text: 'DOM diffing algorithm', id: 3 },
    ],
    correctAnswerId: 0,
    moreInfoUrl:
      'https://github.com/getify/You-Dont-Know-JS/blob/master/async%20%26%20performance/ch5.md#worker-environment',
    explanation: 'Web workers do not have access to the DOM',
},

**Comment by austintackaberry** [comment]
You are correct! I will keep this open until someone wants to fix this issue

**Comment by anthonygedeon** [comment]
Is this still open?

**Comment by austintackaberry** [comment]
Looks like this has been fixed. Closing
