### ISSUE TITLE
ChapterRouter - Warning: Each child in an array or iterator should have a unique "key" prop.

### ISSUE THREAD

**Issue by energydev** [austintackaberry/ydkjs-exercises#25]
There is a "unique key prop" warning occurring when going into a set of questions.  Below is a picture. 

![image](https://user-images.githubusercontent.com/12925952/40329253-9625b8fe-5d0e-11e8-8810-43a964523345.png)

**Comment by energydev** [comment]
I've seen this issue before and can tackle this one.

**Comment by energydev** [comment]
Do we want to consider adding an ID field to the Questions objects? This would allow us to have a unique key that isn't the index. This would provide more flexibility according to this article. Using the index, which is the default, can cause issues if the ordering of the items is changed.

https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318


const Ch1Questions = [
  {
    question: "How many expressions are in the following statement: a = b * 2;",
    answers: [
      {
        answer: "one",
        isCorrect: false
      },
      {
        answer: "two",
        isCorrect: false
      },
      {
        answer: "three",
        isCorrect: false
      },
      {
        answer: "four",
        isCorrect: true
      }
    ]
  },

**Comment by austintackaberry** [comment]
Thanks for opening this issue! It looks like we have this issue in `ChapterRouter` and in `Question`.

For `ChapterRouter`, I think a good solution would be to make the key equal to the path, since the path is a unique identifier.

```javascript
        {chapter.questions.map((question, index) => {
          return (
            <Route
              path={bookUrl + chapter.url + "/q" + (index + 1)}
              render={() => (
                <Question
                  baseUrl={bookUrl + chapter.url}
                  index={index + 1}
                  question={question}
                  numberOfQuestions={chapter.questions.length}
                />
              )}
            />
          );
        })}
```

As for `Question`, I think you are correct in that there is no good solution without having to add ids to the data object. Having said that, we could just make the ids 1, 2, 3, and 4. Per the React docs, the ids do not need to be globally unique, only within the context of the array. So maybe something like this:

```javascript
{
  question: "How many expressions are in the following statement: a = b * 2;",
  correctAnswer: "four",
  incorrectAnswers: [
    {
      answer: "one",
      id: 1
    },
    {
      answer: "two",
      id: 2
    },
    {
      answer: "three",
      id: 3
    }
  ]
}
```
Let me know what you think!

**Comment by energydev** [comment]
Lots of great ideas! I'll take a look at these ideas and the ones from Explanation and Force Single Answer and get back with you.

**Comment by rosaxny** [comment]
Would it make a difference if you grouped all the answers together and then checked if the selected answer was the correct answer? 
```{
  question: "How many expressions are in the following statement: a = b * 2; ?",
  ordered: true,
  answers: [
    {answer: "one", id: 0},
    {answer: "two", id: 1},
    {answer: "three", id: 2},
    {answer: "four", id: 3}
  ],
  correct: "four"
  }

**Comment by austintackaberry** [comment]
Ooh I like that idea. But I think we should check that it is the correct answer via its id instead of its value:

```javascript
  question: "How many expressions are in the following statement: a = b * 2; ?",
  ordered: true,
  answers: [
    {answer: "one", id: 0},
    {answer: "two", id: 1},
    {answer: "three", id: 2},
    {answer: "four", id: 3}
  ],
  correctAnswer: {id:3}
  }
```

**Comment by energydev** [comment]
I also like the idea of grouping all the answers into one array and then referencing the correct answer by id. I'd, also like to propose renaming ordered to something like "orderById". This provides more clarity as to the preferred ordering, as ordered could refer to something like the answers are already ordered.

I'd also like to propose adding an id to the question itself. This would allow us to use it as the key to resolve the warning instead of the longer url.

  id: 0
  question: "How many expressions are in the following statement: a = b * 2; ?",
  orderById: true,
  answers: [
    {answer: "one", id: 0},
    {answer: "two", id: 1},
    {answer: "three", id: 2},
    {answer: "four", id: 3}
  ],
  correctAnswer: {id:3}
  }

**Comment by energydev** [comment]
@austintackaberry if you, by chance, have a format you're excited about by tomorrow/Thursday morning, I've got time to knock out this along with issues #14 and #21.

**Comment by rosaxny** [comment]
Has there been a decision on the format? You could also add a key for the explanation.

```
  question: "How many expressions are in the following statement: a = b * 2; ?",
  ordered: true,
  answers: [
    {answer: "one", id: 0},
    {answer: "two", id: 1},
    {answer: "three", id: 2},
    {answer: "four", id: 3}
  ],
  correctAnswer: 3,
  explanation: "explain why other answers are wrong and why this answer is the best answer"
  }
```

**Comment by austintackaberry** [comment]
Ok, I think the schema below is good. It fixes a lot of the issues with the current schema while still being easy to understand. Thanks for the discussion!

```javascript
question: "How many expressions are in the following statement: a = b * 2; ?",
  orderedById: true,
  answers: [
    {text: "one", id: 0},
    {text: "two", id: 1},
    {text: "three", id: 2},
    {text: "four", id: 3}
  ],
  correctAnswerId: 3,
  explanation: "explain why other answers are wrong and why this answer is the best answer"
  }
```

**Comment by nikrb** [comment]
@energydev do you still have this in hand?

**Comment by energydev** [comment]
@nikrb @austintackaberry I can make these changes today.
