### ISSUE TITLE
[Mobile] - Overlapping text upon viewing chapters of any book

### ISSUE THREAD

**Issue by kozlowsm** [austintackaberry/ydkjs-exercises#28]
**Description:**
When viewing the site on a mobile device, selecting any of the six books results in overlapping text of the chapter titles.

**Environment:**
Device- iPhone 8
OS- iOS 11.3.1
Browser- Safari

**Steps to reproduce:**
1. Navigate to ydkjs-exercises.com on a mobile device
2. Select One of six YDKJS books
3. View overlapping text of chapter titles

**Expected Result:**
Upon selecting a book title, user sees text clearly with no overlapping of characters

**Actual Result:**
Upon selecting a book title, user sees overlapping text that is difficult to read

**Images:**
![screen shot 2018-05-21 at 6 08 40 pm](https://user-images.githubusercontent.com/22461040/40332836-9417e798-5d23-11e8-978a-157e5ad5caed.png)
![screen shot 2018-05-21 at 6 08 58 pm](https://user-images.githubusercontent.com/22461040/40332842-9807f0a0-5d23-11e8-9ffe-fe842fbbbb7e.png)

**Comment by kevinYCKim33** [comment]
I will take a crack at this.

**Comment by kevinYCKim33** [comment]
https://github.com/austintackaberry/ydkjs-exercises/pull/29
