### ISSUE TITLE
App breaks when user clicks on chapter that doesn't have any questions

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#33]
Instead of silently breaking and showing a cryptic error message in the console, we should display some sort of message telling the user something like:

"There are currently no questions for this chapter :(, but you can change that! Feel free to submit a pull request to this project here: https://github.com/austintackaberry/ydkjs-exercises"

**Comment by kevinYCKim33** [comment]
I'll try my hand at this.

**Comment by austintackaberry** [comment]
Sounds good! :+1:

**Comment by kevinYCKim33** [comment]
https://github.com/austintackaberry/ydkjs-exercises/pull/37
