### ISSUE TITLE
Set up some sort of state management system

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#4]
There needs to be a way for the app to keep track of the user's answers. Whether it is client-side state, local storage, or in a database on a server.

I feel like people won't want to have to make a username and password for this web app. Perhaps, the first step would be to have app state that gets saved in local storage. That way the user won't lose all their info when they reload the browser, and they don't have to log in.

Maybe this would be a good use case for the Context API?

**Comment by nikrb** [comment]
I'd suggest IndexedDB rather than local storage.
If react state is used at the top to read/hold the data we could play with context, that would be fun!

**Comment by austintackaberry** [comment]
Ooh I hadn't heard of IndexedDB, but it looks nice. I would also enjoy trying out the context api! Let me know what you plan to work on, so that we don't duplicate any work! 🙂

**Comment by nikrb** [comment]
I planned to flesh out tests for the remaining components.
Just FYI there are libraries that ease use of IndexedDB. I tried a couple, but if I recall correctly, Dexie seemed the best at the time.

**Comment by austintackaberry** [comment]
Sounds good!

**Comment by austintackaberry** [comment]
I'm going to play around with the Context API and see how it works for our use case
