### ISSUE TITLE
Add a 404 page

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#44]
Currently, when a user tries to access a route that does not exist, they get a page that looks like this:

![screenshot from 2018-05-29 01-19-05](https://user-images.githubusercontent.com/29493001/40646567-6442f718-62de-11e8-98f2-dabc78d59e19.png)

We should have a message that tells the user the page they requested does not exist. And it should probably provide a link to the home page.

Feel free to get as creative (or not creative) as you want!

**Comment by ka-rl** [comment]
I can work on this issue
