### ISSUE TITLE
404 message does not show up for nested routes

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#47]
404 message displays for main routes: https://ydkjs-exercises.com/ghkj, but not nested routes: https://ydkjs-exercises.com/up-going/fds

**Comment by jrobind** [comment]
Hi @austintackaberry , I'd like to take a look at this if that's ok!

**Comment by austintackaberry** [comment]
All yours! :slightly_smiling_face:

**Comment by austintackaberry** [comment]
I am leaving this open because there are still routes that aren't picked up by the 404 page:

/up-going/ch1/fdsdf
/up-going/ch1/q1/fdsfds

**Comment by VikasMadan** [comment]
I would like to take a look at the remaining routes, if no one else is tackling this. Please let me know.

**Comment by austintackaberry** [comment]
It's all you!

**Comment by austintackaberry** [comment]
https://github.com/austintackaberry/ydkjs-exercises/pull/50
