### ISSUE TITLE
Change userAnswerIndex to userAnswerId in Question component? 

### ISSUE THREAD

**Issue by energydev** [austintackaberry/ydkjs-exercises#52]
Now that the answers have an id and we may randomize their ordering, would it make sense to change userAnswerIndex to userAnswerId in the Question component?

class Question extends Component {
  constructor() {
    super();
    this.state = { userAnswerIndex: null, answerSubmitted: null, error: false, correctAnswer: null };
  }

**Comment by nikrb** [comment]
I believe we're changing the state shape somewhat so I think we could probably do with an issue to cover this - changing to userAnswerId could be a task in that issue perhaps?

**Comment by austintackaberry** [comment]
I think this is a good thing to fix now. It is a bit misleading as it reads now. @energydev do you want to create a PR?

**Comment by energydev** [comment]
@austintackaberry yes, I can take this on. I should be able to get to this by Tuesday at the latest.
