### ISSUE TITLE
Disable submit and radio buttons after answer submission

### ISSUE THREAD

**Issue by jrobind** [austintackaberry/ydkjs-exercises#53]
Currently users are able to resubmit answers after submission. Would it not be more appropriate for the submit button - and also the radio buttons - to be automatically disabled after submission? This would be useful for when some form of score calculation feature is implemented in the future (and to also prevent cheating) :smirk:.

I would be happy to work on this!

**Comment by austintackaberry** [comment]
Thanks for opening this issue! However, I think we want to give people the opportunity to try again if they want to. I am not sure how we will handle this when we add scoring, but I do think we should allow the user to control their experience.
