### ISSUE TITLE
material-ui release v1

### ISSUE THREAD

**Issue by nikrb** [austintackaberry/ydkjs-exercises#54]
material-ui version 1 has finally arrived - we should probably update asap.

**Comment by jrobind** [comment]
Hey @nikrb, I updated to https://www.npmjs.com/package/@material-ui/core locally on my machine but it seemed to break the app. I'll see if I can find the error message!

**Comment by austintackaberry** [comment]
I was thinking it might be better to remove material-ui and just use something like https://github.com/paypal/glamorous or https://github.com/emotion-js/emotion. Thoughts?

**Comment by nikrb** [comment]
sounds good to me ... I'm a bit of a fan of styled components

**Comment by IrritatedEllipses** [comment]
I'm all for that! Can I also throw [Styled Components into the ring?](https://www.styled-components.com/)

**Comment by austintackaberry** [comment]
Go for it! Want to open up another issue? I'm going to go ahead and close this one.
