### ISSUE TITLE
Add prettier git hook to ensure consistent styling

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#58]
Contributors might have different local styling configurations which is fine, but it can cause unnecessary changes that clutter up the diff.

If there was a git hook that applied a standard styling convention after committing changes, then the commits would be clean and would not include unnecessary non-standard styling changes.

**Comment by nikrb** [comment]
I can look into this. Thinking we should run test and lint before push.

**Comment by austintackaberry** [comment]
Yeah, that's a good idea. Maybe the test and lint should be opt-in? I don't want it to discourage first-time contributors from contributing

**Comment by austintackaberry** [comment]
https://github.com/austintackaberry/ydkjs-exercises/pull/64

**Comment by austintackaberry** [comment]
I noticed in recent commits that there were some styling changes that were made which suggests that perhaps the prettier styling isn't getting applied to the commits?

**Comment by nikrb** [comment]
if I recall correctly, I didn't apply the prettier changes initially as I expected there to be some changes regarding the styling. I think the pr was merged before I ran all the code through it, so I then thought the changes would come in piecemeal as the different files were edited.

If you feel it would be better, I could create a pr *just* to run prettier through all the files.

Also I noticed you changed some single quotes to double quotes. I think generally single quotes are used although I personally prefer double quotes, ala crockford :)

**Comment by austintackaberry** [comment]
Everyone has their own local prettier config which will change minor details like single to double quotes, spacing, etc. Personally, I am not too picky about styling. I just don't want to clutter up the diffs.

That is why we should have prettier run as a [git hook](https://www.atlassian.com/git/tutorials/git-hooks)

That way, regardless of how everyone's env is set up locally, the code on github will always be styled the same.

**Comment by nikrb** [comment]
I'm no expert with prettier, but the config is in the [repo](https://github.com/austintackaberry/ydkjs-exercises/blob/master/prettier.config.js). Surely if everyone has their own local prettier config it's going to be chaos?
It is run as a [precommit](https://github.com/austintackaberry/ydkjs-exercises/blob/c4f1de8835fe20ea20a1a01863fbe87bf8e79430/package.json#L60) git hook to the best of my knowledge, which is why files won't be pretty-fied until they are changed .
I was suggesting we run all files through prettier as a pr as a starting point for future dev.

**Comment by austintackaberry** [comment]
Ah I see. So it is there, but it won't go into effect until each of the files are changed. My bad, I misunderstood. I'll re-close this issue.
