### ISSUE TITLE
Bug: Clicking next takes to next url for question but no question displays

### ISSUE THREAD

**Issue by energydev** [austintackaberry/ydkjs-exercises#60]
Clicking Next results in the URL changing but no next question displaying.

![image](https://user-images.githubusercontent.com/12925952/41006819-b421f698-68e8-11e8-9a1c-4e8ca6e67112.png)

**Comment by energydev** [comment]
Since, I'm already going to be in the Question.JS code tonight, I'll see if I can find what might be causing this.

**Comment by energydev** [comment]
@austintackaberry this appears to be likely related to the changes in ChapterRouter.js related to adding the ScoreContext. I'll leave further review to those working on this item.

**Comment by austintackaberry** [comment]
Sounds good, I'll take a look
