### ISSUE TITLE
Migrate from Material-UI to Styled Components

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#62]
I think we should move away from Material-UI, and @nikrb and @IrritatedEllipses were interested in using styled components, so that is what we will use.

Not sure if we want one person to work on this for the whole app or migrate page by page? Open to thoughts.

- [x] Splash page
- [x] Book page
- [x] Chapter page
- [x] Question page

**Comment by IrritatedEllipses** [comment]
My current learning point is documentation so this question may stem from that:

Is the accepted protocol in situations like implementing aesthetic design to talk about what we'd like the app to look like and then design? Or to make a quick mock up and then share the idea? I'm sorry if this seems a pedantic question.

**Comment by nikrb** [comment]
@austintackaberry suggest you create each file as a task in your original post. I can help with the code. Perhaps @IrritatedEllipses is offering to do the design in the [above](https://github.com/austintackaberry/ydkjs-exercises/issues/62#issuecomment-395098422) comment?

**Comment by nikrb** [comment]
@IrritatedEllipses forgive me if it's too soon to ask, but wondering if you are willing to work on a design. The subject has come up in #59 .

**Comment by IrritatedEllipses** [comment]
@nikrb So sorry for taking so long to answer you. I've realized I'm a bit out of my element and I'm struggling to catch up on React. I'm really wanting to tackle this so I'm trying to catch up as much as I can. Judging from my progress so far I should be able to start contributing on 6/18/18

**Comment by nikrb** [comment]
@IrritatedEllipses no worries, thanx for responding and taking part.
I would suggest the design per se doesn't really need react so it would be great if you could put some pics together with your ideas.
If I've got the wrong end of the stick and you were wanting to do some coding that's kool ... but we still need someone to hash out a design/colour theme.
@austintackaberry depending on 'ellipses' response, perhaps we should create a new issue requesting anyone with design skills to chip in?

**Comment by nikrb** [comment]
ok fair enough I'll make a start on it.

**Comment by austintackaberry** [comment]
https://github.com/austintackaberry/ydkjs-exercises/pull/81
