### ISSUE TITLE
Remove "Chapter 3: Into YDKJS" from "Up and Going" page

### ISSUE THREAD

**Issue by kozlowsm** [austintackaberry/ydkjs-exercises#72]
Chapter 3 in the book "Up & Going" is basically an overview of the material that will be presented to the readers in the coming books. Given that it is just an overview, is it necessary to write questions for the chapter?

**Comment by nikrb** [comment]
reasonable point, though I think perhaps some *big picture* questions might be appropriate?

**Comment by austintackaberry** [comment]
I skimmed through the chapter, and I feel like any questions we could add would just seem like filler questions, so I'm good with having that chapter removed.

**Comment by austintackaberry** [comment]
I think I have decided that the best way to handle this is to not show this chapter on the Up and Going page.

As for how to implement this...maybe since this is a one-off case we can just delete it? Since it is the last chapter in the book, it won't throw off any of the indices or routes. Thoughts?

**Comment by hakabuk** [comment]
I'm currently going through the book, and I honestly made an effort to think of questions. However, the more I read the more it seemed justified to leave the entire chapter out of the exercises, as suggested above. Having a not clickable chapter would even be a bit confusing, IMO.

**Comment by austintackaberry** [comment]
Ok, so let's just delete it from the data. Any takers??

**Comment by austintackaberry** [comment]
Go for it! :slightly_smiling_face:
