### ISSUE TITLE
Use propTypes?

### ISSUE THREAD

**Issue by radotreyes** [austintackaberry/ydkjs-exercises#75]
Small issue, I just noticed that we're not currently using `propTypes` in our components. Might make it easier for newcomers to navigate and contribute to the project as it grows if we did. Thoughts?

**Comment by austintackaberry** [comment]
I haven't ever used them, but it seems like a good idea to me if you or anyone else wants to add them!

**Comment by radotreyes** [comment]
I can take care of it. I'll take a look later this afternoon.

**Comment by radotreyes** [comment]
I got carried away with #59/#74 yesterday. I'll take a look tonight, I promise. 😅
