### ISSUE TITLE
Rethink layout for Question page

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#76]
![screenshot from 2018-06-16 00-00-15](https://user-images.githubusercontent.com/29493001/41496601-519208c0-70f8-11e8-815b-d30c1a56ec3a.png)

Right now the design/layout looks clunky. Given that the explanations could get long, it might make sense for them to be below the navigation buttons, so that there is no limit to how long they can be.

We should make sure that the navigation buttons stay in the same location regardless of how long the question is, whether the explanation is shown or hidden, etc.

Maybe the navigation buttons should be to the right/left of the question rather than below it?

Open to other ideas, just think the current layout needs some help!

**Comment by nikrb** [comment]
I was thinking put the buttons at the top so the question could grow as needed.
Perhaps consider putting the buttons in the sidebar?

**Comment by austintackaberry** [comment]
Yeah, the top could work. If the buttons were to the right/left of the question, they would be arrows or something instead of traditional buttons. We could do some sort of animation as well.

**Comment by kevinYCKim33** [comment]
![Codecademy Style](https://i.imgur.com/El3nVS5.png)

How about something like this?  

The explanation goes under the Q section, and we can make it scrollable if it's a particularly length explanation?

**Comment by kevinYCKim33** [comment]
![Mobile-View](https://i.imgur.com/EKBQZoT.png)

Here's what it could look like in mobile.

**Comment by kevinYCKim33** [comment]
https://www.codecademy.com/skills/uk-quizzes

**Comment by austintackaberry** [comment]
Thanks for showing this, it's nice to see how similar sites handle the layout. The main difference is that is specifically a quiz which means that users typically go from start to finish. I view YDKJS Exercises as more like practice problems where you can see your progress which means users may want to go back and forth between questions.

Just thinking out loud...we could maybe handle that functionality in the sidebar? Maybe if you are answering questions for Up & Going/Chapter 1 then in the sidebar, you see chapter 1 below Up and Going, and then the list of questions below that. Perhaps, the question you are on currently is highlighted, and you can click to go to other questions. You also have the option to minimize the questions. Thoughts?

**Comment by radotreyes** [comment]
I really like that idea. I think you should be able to fully navigate the app using the sidebar as well. Using the current sidebar as an example:

1. The sidebar's top-level elements are user progress and a list of all books.
2. Each book list item contains a list of chapters for that book. This list is collapsed by default and opens on click.
3. Each chapter list item is also collapsed by default, and when clicked reveals a list of questions.
4. Each question then links to the appropriate page view.

**Comment by kevinYCKim33** [comment]
[Imgur](https://i.imgur.com/SzlmKKj.png)

Hmm something like this then?

**Comment by kevinYCKim33** [comment]
![img](https://i.imgur.com/SzlmKKj.png) Something like this then?

**Comment by austintackaberry** [comment]
Yeah, that is like a perfect picture of what I was thinking! It would be difficult to implement, but that's what makes it fun right ;)

**Comment by radotreyes** [comment]
I think we could implement it even without having user functionality set up, then modify it later to work with whatever permissions we want to give when users are logged in/out 🙂
