### ISSUE TITLE
Bug: Whole container for YDKJS chapter link is clickable

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#77]
![awesomescreenshot-2018-06-16t07-06-00-443z](https://user-images.githubusercontent.com/29493001/41496643-7d7b8582-70f9-11e8-8d8f-a40f3a2314cf.gif)

Only the link itself should be clickable

**Comment by esthercuan** [comment]
Austin, I'd like a stab at this one :)
