### ISSUE TITLE
Chapters that don't have any questions should not be clickable

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#82]
This issue is a result of #72. Originally, I was going to have just Up and Going Ch3 not be clickable, since it shouldn't have any questions given that it is just a preview of YDKJS. However, as I thought about it, I realized that any chapter that doesn't have any questions shouldn't be clickable. Open for discussion 🙂

**Comment by nikrb** [comment]
two penneth ... I prefer feedback when I click on something, nothing worse than not being sure if something is not working or just taking a while - a personal pet peeve.

**Comment by austintackaberry** [comment]
But do you need to go to a whole different page? Maybe when you click, you get a small info popout?

**Comment by austintackaberry** [comment]
I'm also not sure what we should do with Up and Going Ch3

**Comment by nikrb** [comment]
no me either. I think it'll be odd not having any questions though if there's nothing to write questions on I can only think we manufacture some big picture questions loosely related to the other books.

**Comment by austintackaberry** [comment]
Maybe we should leave this open and get other opinions. I don't feel great about any option.

**Comment by kevinsmithwebdev** [comment]
Does it even need to list chapters that don't have questions? Can't those be filtered out?

**Comment by austintackaberry** [comment]
There are many chapters that currently don't have questions but should have questions. We want there to be a "no questions" page to encourage users to contribute.

As for Up and Going Ch3, maybe it would be fine to just leave it off.
