### ISSUE TITLE
.gitignore.exclude

### ISSUE THREAD

**Issue by nikrb** [austintackaberry/ydkjs-exercises#83]
Just noticed we have gained a .gitignore.exclude file ... looks the same as .gitignore to me, do we need it?

**Comment by austintackaberry** [comment]
What is a .gitignore.exclude file? I don't see a need for it

**Comment by radotreyes** [comment]
Whoops, that was me. Not sure how that got there. I'll get rid of it.

**Comment by austintackaberry** [comment]
https://github.com/austintackaberry/ydkjs-exercises/pull/84
