### ISSUE TITLE
Sidebar should show correct answers / total answered questions

### ISSUE THREAD

**Issue by austintackaberry** [austintackaberry/ydkjs-exercises#85]
Not sure the best way to show this, however. We still want the user to see how many questions they have answered in each section and how many questions are in each chapter. Maybe at the top, it should say something like:

"You have answered 3 questions correctly and 1 question incorrectly for a score of 75%"

**Comment by nikrb** [comment]
just thinking out loud ... bit wordy for sidebar? maybe
3 questions <tick mark>
1 question <cross mark>
score 75%
I don't think we need to rush into a decision.

**Comment by radotreyes** [comment]
@austintackaberry are you thinking about handling "correct", "incorrect", and "not answered" differently? Like not factoring in unanswered questions into the total score?

**Comment by austintackaberry** [comment]
Somehow, the user should be able to find the following info in the sidebar:

1.  Number of questions answered correctly / Number of questions answered, and the percentage
2. Total number of questions in each book
3. Total number of questions in each chapter

This issue is about tackling 1.

**Comment by radotreyes** [comment]
How about something like this? Quick mockup I did.

<img width="335" alt="image" src="https://user-images.githubusercontent.com/25578179/41740824-1bf2a6a2-754e-11e8-8eb5-393443f85427.png">

**Comment by radotreyes** [comment]
Here we go 😅 I'll leave the other one up in case we decide to take that option (displaying score as a percentage of total rather than answered). Sorry for misunderstanding.
<img width="332" alt="image" src="https://user-images.githubusercontent.com/25578179/41744683-69ff10be-7559-11e8-90dc-98080792db6d.png">

**Comment by nikrb** [comment]
looks awesome.
just thinking out loud ... bit too detailed for sidebar perhaps? more of a summary required for sidebar (without the individual questions), full details (with questions) in a full page overview?

**Comment by radotreyes** [comment]
@nikrb I see your point, and looking at it now I agree. Could probably do without the individual question list. 

Have any other suggestions for how to kind of intuitively represent score without being verbose? A progress bar is the first thing I thought of, but I'm sure there's another solution that isn't so distracting for the user when they're looking at both the sidebar and the main page.

**Comment by nikrb** [comment]
I think the mock-up is awesome dude.
May be a bit OTT, but we could perhaps colour the whole bar, green for correct, red for incorrect, orange (or just uncoloured) for not attempted.
Let's get some feedback from @austintackaberry  before we forge ahead - it might be just what he was after as it stands.

**Comment by radotreyes** [comment]
For sure! Just spitballing here.

**Comment by austintackaberry** [comment]
I like the idea of the progress section. As a user, it is nice to be able to see my current progress in an intuitive location. But yeah, we need to try to keep it as simple as possible because it would be easy to clutter it up too much.

Here is what I'm thinking:

The progress section has the following:
- Correct: 3
- Incorrect: 5
- Score: 60%
- Unanswered: 20 (maybe not include this one..undecided)

I like the idea of the icons next to the questions based on the 3 possible states: correct, incorrect, unanswered.

If we make the questions be links to the question page, then I don't think we need the links off to the right.

Though, the progress bars look cool in the mockups, and they would be a fun feature to implement, I don't know if they are necessary.

**Comment by kevinsmithwebdev** [comment]
What about, the length of the bar is all the questions, then there is a green portion representing correct answers, a red portion representing wrong answers, and a orange part representing questions skipped. The user can hover over it to get a tooltip with with the numbers?

I'm just thinking out loud here.

**Comment by austintackaberry** [comment]
Ooh I like that idea! But I do think there should be words as well.

Status bar at the top: length of bar represents the number of questions, green is correct answers, red is incorrect answers, and no color means unanswered.

Then below the status bar maybe something like:

"You have correctly answered **3** questions out of a total of **5** questions for a score of **60%**, and you have **15** questions left to answer.

**Comment by austintackaberry** [comment]
Thinking about opening a new issue with specific tasks, so that we can finally code this thing. But before I do, I want to make sure we have a mockup to go off of. Thanks @radotreyes for sending me your mockup file. Just put this together:

![20180621-score-austin 001](https://user-images.githubusercontent.com/29493001/41874933-31685d5a-787e-11e8-8c3d-600c85e3705e.jpeg)
