### ISSUE TITLE
Add markdown capability to allow simple styling of questions

### ISSUE THREAD

**Issue by kevinsmithwebdev** [austintackaberry/ydkjs-exercises#88]
I propose adding some simple markdown ability to the text, for example italics, bold, inline code blocks, etc. This would greatly enhance the readability and create a more polished look.

I see that there are modules like "react-markdown".

Then a style guide could be generated so we are all using them in the same why for the same types of text.

**Comment by austintackaberry** [comment]
Briefly looking at react-markdown, it seems like a good solution to this problem. It wouldn't force us to make any major architectural changes, and it seems easy to use.

The only other option I see is that we just put HTML elements in our json and use `dangerouslySetInnerHTML`, but that seems less than ideal.

I'm curious if anyone has any other potential solutions.

**Comment by radotreyes** [comment]
On board with react-markdown! Would make our problem set descriptions significantly more accessible. I think it'd be nice to have each question (at least the problem descriptions and solutions) contained in separate modules and this seems like a great solution.

**Comment by kevinsmithwebdev** [comment]
Let me take a whack at this. I'll implement the react-markdown for the question and answer fields.

**Comment by austintackaberry** [comment]
Awesome!

**Comment by austintackaberry** [comment]
Just thinking out loud...do we need markdown or can we just use JSX? I feel like JSX can do most everything that markdown can do, arguably more.

**Comment by kevinsmithwebdev** [comment]
Whatever works. Sorry, I haven't finished this, I got bogged down with a
React Native freelance job. I have the Markdown 90% working, but if you
want to take it in a different direction, I won't be offended.

**Comment by austintackaberry** [comment]
Let's go with `react-markdown`. If it isn't working for us, we can always remove it.

Is there something you're stuck on?

**Comment by kevinsmithwebdev** [comment]
No, like I said, I've just been bogged down with a paying React Native
freelance project. I'll see you on Sunday, we can take a look at it then.

Regards,
Kevin Smith

**Comment by austintackaberry** [comment]
No problem, just checking to see if there was anything I could help with regarding that remaining 10%. See you Sunday!
