### ISSUE TITLE
Adding URL's of specific chapter headings to each question 

### ISSUE THREAD

**Issue by hakabuk** [austintackaberry/ydkjs-exercises#90]
I love that there's a link to the chapter above every question, but I feel that since the entire book series is (so generously) shared on github - we can be even more specific. 

I suggest discussing an option to add links to the section of the chapter that explains the question, [like so](https://github.com/getify/You-Dont-Know-JS/blob/master/up%20%26%20going/ch1.md#expressions). It could be revealed next to the answer explanation for further reading, OR shared as a hint ("Not sure? Click here to refresh your memory"). 

The reason for is the more complex the chapter gets, the harder it will be to locate the explanation for a specific question so I feel the general link to the chapter might be insufficient on more advanced topics.

I can think of two minor (IMO) 'cons' for this: 
1. More updates if the content of the books (specifically the headings) change.
2. Learners might learn more if they search for additional resources on their own, rather than return to the previous resource. 

Please feel free to share your thoughts. This is just a suggestion that came to me while updating new questions and looking at the question data structure. IMO even if we don't display the link in the interface right away - we could for now just add the link to the each question's object as a future option. I'm happy to help with updating URL's for existing questions, if need be.

**Comment by nikrb** [comment]
we needed a new issue for this, orignally touch on in issue #14

**Comment by austintackaberry** [comment]
Agreed, let's do it. @hakabuk do you want to work on this? If not, that's ok too. Thanks for opening this issue!

**Comment by hakabuk** [comment]
Sure thing! I'm more than happy to do this. Btw, I plan to use the key `url` (lowercased). Please feel free to share if there are other suggestions/conventions.

**Comment by austintackaberry** [comment]
Thanks for taking this on! `url` could be a little confusing...people might think that it corresponds to the question's url (https://ydkjs-exercises.com/up-going/ch1/q1). I think something like `moreInfoUrl` or `moreInfoLink` would be good options.

**Comment by hakabuk** [comment]
That makes sense, thanks! Will do.

**Comment by austintackaberry** [comment]
Leaving this open until the urls are implemented and working correctly on Question.js

**Comment by hakabuk** [comment]
Thanks, and I apologise for misunderstanding. I'm excited to keep working on this. 
Will let you know if I have any questions

**Comment by austintackaberry** [comment]
No need to apologize! I'm all for gradual improvement

**Comment by hakabuk** [comment]
There's a bit of redundancy with the upper chapter link: 
![screen shot 2018-06-28 at 13 43 35](https://user-images.githubusercontent.com/16784959/42035003-ba354ef6-7ad9-11e8-89d5-ef5967d6e7d7.png)

Please share if there are any other adjustments you feel can be done to improve this.

**Comment by austintackaberry** [comment]
I think we should get rid of the text at the top. I think the more natural place for it is after the explanation.

I also think that maybe "More information here" might be better than "Github link to the chapter section". On hover, the user can see what the url is if they want to. Thoughts?
